spring.application.name=Petistaan-Gateway-Server
server.port=8080
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
spring.cloud.gateway.server.webflux.routes[0].id=petistaan-ownerms
spring.cloud.gateway.server.webflux.routes[0].uri=lb://petistaan-ownerms
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/petistaan/owners/**
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=After=2026-03-03T10:00:00+05:30[Asia/Kolkata]
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[1].id=petistaan-petms
spring.cloud.gateway.server.webflux.routes[1].uri=lb://petistaan-petms
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/petistaan/pets/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[2].id=petistaan-mailms
spring.cloud.gateway.server.webflux.routes[2].uri=lb://petistaan-mailms
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/petistaan/mails
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
