spring.application.name=Petistaan-Gateway-Server
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
spring.cloud.gateway.server.webflux.routes[0].id=petistaan-ownerms
spring.cloud.gateway.server.webflux.routes[0].uri=lb://petistaan-ownerms
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/petistaan/owners/**
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=After=2026-03-04T20:00:00+05:30[Asia/Kolkata]
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[1].id=petistaan-petms
spring.cloud.gateway.server.webflux.routes[1].uri=lb://petistaan-petms
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/petistaan/pets/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[2].id=petistaan-mailms
spring.cloud.gateway.server.webflux.routes[2].uri=lb://petistaan-mailms
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/petistaan/mails
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
