spring.application.name=Petistaan-OwnerMS
spring.config.import=configserver:http://localhost:8888
pet.service.base.url=http://petistaan-petms/pets
mail.service.base.url=http://petistaan-mailms/mails
eureka.client.service-url.defaultZone=http://localhost:8761/eureka,http://localhost:8762/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
