spring.application.name=Petistaan-OwnerMS
spring.config.import=configserver:http://localhost:8888
pet.service.base.url=http://localhost:8082/pets
mail.service.base.url=http://petistaan-mailms/mails
spring.cloud.discovery.client.simple.instances.petistaan-mailms[0].uri=http://localhost:8083
spring.cloud.discovery.client.simple.instances.petistaan-mailms[1].uri=http://localhost:8084
