spring.application.name=Petistaan-OwnerMS
spring.config.import=configserver:http://localhost:8888
pet.service.base.url=http://petistaan-petms/pets
mail.service.base.url=http://petistaan-mailms/mails
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
resilience4j.retry.instances.petRetry.maxAttempts=3
resilience4j.retry.instances.petRetry.waitDuration=1s
resilience4j.retry.instances.petRetry.enableExponentialBackoff=true
resilience4j.retry.instances.petRetry.exponentialBackoffMultiplier=2
resilience4j.circuitbreaker.instances.petCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.petCircuitBreaker.minimumNumberOfCalls=4
resilience4j.circuitbreaker.instances.petCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.petCircuitBreaker.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.petCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.petCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
