spring.application.name=Petistaan-OwnerMS
spring.config.import=consul:
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.config.format=properties
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
resilience4j.retry.instances.petRetry.maxAttempts=3
resilience4j.retry.instances.petRetry.waitDuration=1s
resilience4j.retry.instances.petRetry.enableExponentialBackoff=true
resilience4j.retry.instances.petRetry.exponentialBackoffMultiplier=2
resilience4j.circuitbreaker.instances.petCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.petCircuitBreaker.minimumNumberOfCalls=4
resilience4j.circuitbreaker.instances.petCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.petCircuitBreaker.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.petCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.petCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans
